# Generated by Django 4.0.5 on 2022-10-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_faculty_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='emfdisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('emfimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.emf')),
            ],
        ),
    ]
