# Generated by Django 4.0.5 on 2022-10-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0005_cn_iot_ml_ws_delete_emfdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='emfdisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
