# Generated by Django 4.0.5 on 2022-10-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0008_rename_comments_cndisplay_comments_cn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cn',
            old_name='cie_image',
            new_name='cn_cie_image',
        ),
        migrations.RenameField(
            model_name='cn',
            old_name='title',
            new_name='cn_title',
        ),
        migrations.RenameField(
            model_name='iot',
            old_name='cie_image',
            new_name='iot_cie_image',
        ),
        migrations.RenameField(
            model_name='iot',
            old_name='title',
            new_name='iot_title',
        ),
        migrations.RenameField(
            model_name='ml',
            old_name='cie_image',
            new_name='ml_cie_image',
        ),
        migrations.RenameField(
            model_name='ml',
            old_name='title',
            new_name='ml_title',
        ),
        migrations.RenameField(
            model_name='ws',
            old_name='cie_image',
            new_name='ws_cie_image',
        ),
        migrations.RenameField(
            model_name='ws',
            old_name='title',
            new_name='ws_title',
        ),
    ]
