# Generated by Django 4.1.2 on 2022-10-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_alter_emf_cie'),
        ('dept', '0009_rename_cie_image_cn_cn_cie_image_and_more'),
    ]

    operations = [
    ]
