# Generated by Django 4.1.2 on 2022-10-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0010_merge_20221011_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emf',
            name='cie',
        ),
    ]
